Waygates:
  MAX_AREA: 200
  MENU_SIZE: compact
  WG_NAME_MAX_LENGTH: 18
  WG_DESC_MAX_LENGTH: 100
  WG_NETWORK_NAME_MAX_LENGTH: 18
  WG_CONTROLLER_DISTANCE: 50
  WG_GATE_ACTIVATION_TIME: 20
  WG_GATE_EFFECT_PARTICLES: normal
  WG_GATE_MINIMAL_DISTANCE: 1
  WG_GATE_ICON_CHANGE_CONSUMES: false
  WG_CONTROL_CREATOR_CONSUMES: true
  WG_CONSTRUCTOR_CONSUMES: true
  WG_KEY_CONSUMES: false
  WG_KEY_PERMANENT: false
  WG_ZOMBIE_PIGMAN_ALLOWED: false
  WG_PRIVATE_GATES_ALLOW_TRAVEL: false
  WG_GIVE_PLAYERS_RECIPES: false
  BLOCKS_REQUIRED:
    '1':
      EMERALD_BLOCK: 2
