Waygates:
  MAX_AREA: 200
  WG_NAME_MAX_LENGTH: 18
  WG_DESC_MAX_LENGTH: 100
  WG_NETWORK_NAME_MAX_LENGTH: 18
  WG_GATE_ACTIVATION_TIME: 20
  WG_GATE_MINIMAL_DISTANCE: 1
  WG_CONSTRUCTOR_CONSUMES: true
  WG_KEY_PERMANENT: false
  WG_ZOMBIE_PIGMAN_ALLOWED: false
  BLOCKS_REQUIRED:
    '1':
      EMERALD_BLOCK: 2
