 name: WuufusWaygates
 author: Wuufu
 main: com.github.jarada.waygates.PluginMain
 version: ${project.version}
 prefix: WuufusWaygates
 api-version: 1.13
 softdepend:
   - 'NBTAPI'
   - 'Multiverse-Core'
   - 'MultiWorld'
 commands:
   wg:
     description: Waygates top-level command
     usage: /wg <reload>
     aliases: [wayg, waygates]
 permissions:
   wg.*:
     description: Grants all plugin permissions
     children:
       wg.admin: true
       wg.command.*: true
   wg.all:
     description: Grants all plugin permissions
     children:
       wg.admin: true
       wg.command.*: true
   wg.travel:
     default: true
     description: Can travel anywhere
   wg.craft.*:
     description: Grants access to craft Waygate Constructors and Waygate Keys
     children:
       wg.craft.constructor: true
       wg.craft.key: true
   wg.key.*:
     description: Grants access to use Waygate Keys to use gate controls
     children:
       wg.key.use: true
       wg.key.permanent: true
   wg.create.*:
     description: Create gates and networks
     children:
       wg.create.gate: true
       wg.create.network.*: true
   wg.create.network.*:
     description: Create networks of any type
     children:
       wg.create.network.global: true
       wg.create.network.invite: true
       wg.create.network.fixed: true
       wg.create.network.private: true
   wg.assign.*:
     description: Assign flags to gates
     children:
       wg.assign.alwayson: true
       wg.assign.destination: true
       wg.assign.effect: true
       wg.assign.private: true
       wg.assign.hidden: true
   wg.icon.change:
     description: Change icon on gates using items
   wg.view.*:
     description: View all restricted information
     children:
       wg.view.coords: true
   wg.command.*:
     description: Use all commands
     children:
       wg.command.item.*: true
       wg.command.reload: true
       wg.command.world.*: true
   wg.command.item.*:
     description: Commands to gain items
     children:
       wg.command.item.constructor: true
       wg.command.item.key: true
       wg.command.item.lock: true
   wg.command.reload:
     description: Reload Config
   wg.command.world.*:
     description: Use of commands for gate management in worlds
     children:
       wg.command.world.list: true
       wg.command.world.delete: true
   wg.command.world.list:
     description: Use of command to list gates in world
   wg.command.world.delete:
     description: Use of command to delete all gates in world
   wg.network.*:
     description: Add gates you create to any fixed/global/system network
     children:
       wg.network.overworld: true
       wg.network.nether: true
       wg.network.underworld: true
       wg.network.the_end: true
       wg.network.ocean: true
       wg.network.global: true
       wg.network.fixed: true
   wg.player:
     description: Standard permission set
     children:
       wg.travel: true
       wg.craft.*: true
       wg.key.use: true
       wg.assign.*: true
       wg.create.gate: true
       wg.create.network.private: true
       wg.create.network.invite: true
       wg.icon.change: true
       wg.view.*: true
   wg.player.global:
     description: Global permission set
     children:
       wg.player: true
       wg.create.network.global: true
       wg.network.*: true
   wg.bypass:
     description: Access private/hidden gates
   wg.keep.*:
     description: Avoid consumption of constructor and key
     children:
       wg.keep.constructor: true
       wg.keep.key: true
   wg.admin:
     description: Admin permission set
     children:
       wg.player.global: true
       wg.create.network.fixed: true
       wg.bypass: true
       wg.keep.*: true
