 name: WuufusWaygates
 author: Wuufu
 main: com.github.jarada.waygates.PluginMain
 version: ${project.version}
 prefix: WuufusWaygates
 api-version: 1.13
 commands:
   wg:
     description: Waygates top-level command
     usage: /wg <reload>
 permissions:
   wg.*:
     description: Grants all plugin permissions
     children:
       wg.admin: true
       wg.command.*: true
   wg.travel:
     default: true
     description: Can travel anywhere
   wg.key.*:
     description: Grants access to use Waygate Keys to use gate controls
     children:
       wg.key.use: true
       wg.key.permanent: true
   wg.create.*:
     description: Create gates and networks
     children:
       wg.create.gate: true
       wg.create.network: true
   wg.assign.*:
     description: Assign all the things
     children:
       wg.assign.gate.*: true
       wg.assign.network.*: true
   wg.assign.gate.*:
     description: Assign flags to gates
     children:
       wg.assign.gate.destination: true
       wg.assign.gate.private: true
       wg.assign.gate.hidden: true
   wg.assign.network.*:
     description: Assign network type on creation
     children:
       wg.assign.network.global: true
       wg.assign.network.invite: true
   wg.command.*:
     description: Use all commands
     children:
       wg.command.reload: true
       wg.command.world.*: true
   wg.command.reload:
     description: Reload Config
   wg.command.world.*:
     description: Use of commands for gate management in worlds
     children:
       wg.command.world.list: true
       wg.command.world.delete: true
   wg.command.world.list:
     description: Use of command to list gates in world
   wg.command.world.delete:
     description: Use of command to delete all gates in world
   wg.network.*:
     description: Add gates you create to any global/system network
     children:
       wg.network.overworld: true
       wg.network.nether: true
       wg.network.underworld: true
       wg.network.the_end: true
       wg.network.ocean: true
       wg.network.global: true
   wg.player:
     description: Standard permission set
     children:
       wg.travel: true
       wg.key.use: true
       wg.create.*: true
       wg.assign.gate.*: true
       wg.assign.network.invite: true
   wg.player.global:
     description: Global permission set
     children:
       wg.player: true
       wg.assign.network.global: true
       wg.network.*: true
   wg.bypass:
     description: Access private/hidden gates
   wg.admin:
     description: Admin permission set
     children:
       wg.player.global: true
       wg.bypass: true
